### ISSUE TITLE
MQTT Broker Authentication

### ISSUE THREAD

**Issue by unispehere** [meltaxa/solariot#14]
Great work with incorporating the modbus decryption in to your script. Note that you just need to add an extra line in for MQTT broker authentication to work.

try: 
  mqtt_client = mqtt.Client('pv_data')
  **mqtt.username_pw_set(config.mqtt_username,config.mqtt_password)**
  mqtt_client.connect(config.mqtt_server, port=config.mqtt_port)
except:
  mqtt_client = None

**Comment by meltaxa** [comment]
Done. Also the branch update contains the new SungrowModbusTcpClient library that has recently been made available in pypi.

**Comment by meltaxa** [comment]
Merged to master.
