### ISSUE TITLE
Grafana visual issue

### ISSUE THREAD

**Issue by TrentBartlem** [meltaxa/solariot#2]
<img width="829" alt="screen shot 2018-10-11 at 10 20 44 am" src="https://user-images.githubusercontent.com/171650/46773197-6a9b5a80-cd3f-11e8-92bb-37ca4a2b0284.png">

Chrome 69.0.3497.100

**Comment by meltaxa** [comment]
Hi Trent. That's my live site showing the issue (as opposed to the git code). I've fixed it though: 
<img width="645" alt="screen shot 2018-10-14 at 12 40 18 pm" src="https://user-images.githubusercontent.com/19274980/46912009-5d37d780-cfae-11e8-8ec8-353381560184.png">
