### ISSUE TITLE
PVOutput support

### ISSUE THREAD

**Issue by meltaxa** [meltaxa/solariot#22]
Enhancement to upload Solariot metrics to pvoutput.org.

API specs: https://pvoutput.org/help.html#api-spec

**Comment by michael-robbins** [comment]
PR's up, just needs testing once my solar inverter is online again... why can't the sun just stay up all the time...

**Comment by michael-robbins** [comment]
Tested it out in my PR and it all seems to be working and publishing nicely!

Looking at `modbus-sungrow-sh5k.py` I can't see any of the `v1` through `v4` attributes though, are they different names?

Currently I've got:
```
            if "daily_power_yield" in metrics:
                parameters["v1"] = metrics["daily_power_yield"]

            if "total_active_power" in metrics:
                parameters["v2"] = metrics["total_active_power"]

            if "daily_energy_consumption" in metrics:
                parameters["v3"] = metrics["daily_energy_consumption"]

            if "power_meter" in metrics:
                parameters["v4"] = metrics["power_meter"]
```

**Comment by meltaxa** [comment]
As per comments in your PR, I've made some updates to handle different modbus maps and also stay within the API rate limits.
