### ISSUE TITLE
Github Actions integration

### ISSUE THREAD

**Issue by michael-robbins** [meltaxa/solariot#28]
If I was to PR a Github Actions file that built and published a docker image... how would that sound?

We can publish either to githubs docker image registry or to docker hub as well (or both!)

**Comment by michael-robbins** [comment]
@meltaxa I'm not across publishing docker images to githubs registry, can suss out what you need to do/turn on/etc...

For docker hub if you want to be the owner, just go in and register and create a solariot and we'll throw the API KEY in as a secret variable into the repo

**Comment by meltaxa** [comment]
Sounds good. Let's do both. I'll ping you the API keys when they are setup.

**Comment by michael-robbins** [comment]
Ahh mad, yeah I was using that integration before I moved it all to Github Actions for a side project of mine.

We can just stick with this until there's a burning need to use something else I guess, less fiddly bits!

**Comment by michael-robbins** [comment]
I think just master/latest is fine, as I build images separately for my branches when testing out stuff

**Comment by meltaxa** [comment]
Ended up using Github Actions so we could have ARM platform images too. The Docker images works fine on my Raspberry Pi.
