### ISSUE TITLE
Raspberry pi failure

### ISSUE THREAD

**Issue by takethisusernameidareyou** [meltaxa/solariot#3]
Hi

I have a raspberry pi running raspbian with grafana/influxdb installed and I tried to run the script and I get the following error 

root@grafpi:~/sunnyboy/solariot# ./solariot.py
Traceback (most recent call last):
  File "./solariot.py", line 40, in <module>
    print "Load config %s" % config.model
AttributeError: 'module' object has no attribute 'model'

Some stuff that might help I hope 
Requirements were installed as per "pip install -r requirements.txt" 
Python 2.7.9 (default, Sep 17 2016, 20:26:04)
pip 1.5.6 from /usr/lib/python2.7/dist-packages (python 2.7)

**Comment by meltaxa** [comment]
The error indicates that the model setting is not defined in your config.py file. For example, model = "sma-SBn_n-1AV-40". Refer to the config-example.py file.
